annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 2023.12.2
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.12
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.0.14
- condition: influxdb.enabled
  name: influxdb
  repository: https://charts.bitnami.com/bitnami
  version: 5.3.5
description: Home Assistant
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
keywords:
- home-assistant
- hass
- homeassistant
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: home-assistant
sources:
- https://github.com/home-assistant/home-assistant
- https://github.com/cdr/code-server
- https://github.com/k8s-at-home/charts/tree/master/charts/stable/home-assistant
version: 13.4.2
