apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: home-assistant
spec:
  automountServiceAccountToken: true
  containers:
    - image: busybox:latest
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - mountPath: /config
          name: home-assistant
      command: [ 'sleep', '1d']
  volumes:
    - name: home-assistant
      persistentVolumeClaim:
        claimName: home-assistant-home-assistant-0
