@startuml Layer 1 topology (future)

cloud isp
node ont as "fiber ONT"
node wan as "WAN router"
node firewall #line.dotted
node managed_switch as "managed switch"
node router as "Router w/PoE"
node poe as "PoE switch"
node camera1 as "Camera"
node camera2 as "Camera"

frame lab {
    frame x86 as "x86 cluster" {
        node tiny1
        node tiny2
        node tiny3
    }
    frame pis as "Pi cluster" {
        node pi1 as "Pi 1 (zwave)"
        node pi2 as "Pi 2 (kvm)"
        node pi3 as "Pi 3" #line.dotted
    }
}
node wap1 as "WAP"
node wap2 as "WAP"
node wap3 as "WAP"



isp - ont: fiber
ont - wan
wan -- router: uplink
firewall - router: one-legged
router -- wap1: PoE
router -- wap2: PoE
router -- wap3: PoE
router -- managed_switch: uplink
managed_switch -- poe: uplink
poe -- camera1: passive
poe -- camera2: passive
managed_switch - kvm
kvm -- pi1
kvm -- pi2 #line.dashed
kvm -- tiny1: ATX
kvm -- tiny2
kvm -- tiny3
managed_switch --- tiny1
managed_switch --- tiny2
managed_switch --- tiny3
managed_switch --- pi1
managed_switch --- pi2
managed_switch -- pi3 #line.dotted


@enduml
