apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: cloudflared
spec:
  automountServiceAccountToken: true
  containers:
    - image: busybox:latest
      imagePullPolicy: IfNotPresent
      name: busybox
      command: [ 'sleep', '1d']